### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by happyflying-web** [PietroVitiello/ActionRepresentation#8]
Your work is very meaningful to me, but some of the proper nouns and abbreviations in the code are difficult for me to understand. What bothers me the most is how to reasonably choose the configuration information in the code to meet my needs. Due to the above problems, I cannot run your code successfully. It would be better if you could introduce the steps to make the code run successfully as a demo at your convenience. Thank you very much!

**Comment by PietroVitiello** [comment]
Hi happyflying-web,
Thank you very much for showing your interest.

Yes I do realise that the code is not well documented and it is mostly because I intended for this repo to simply introduce the concept of the Motion Image and to show that it could be used in a network as an additional predicted output by an image decoder. The actual model architectures and pipelines are very standard so I actually believe it is easier for you to reinplement them than actually integrate my codebase into yours.

This being said, I'll try to guide you through the main code that you should be interested in, and I promise it will be very easy for you to go on from there:

- In ```src/Learning/Models/MotionIMG/``` you find the MI-Net architecture and all its variants. In that folder ```models.py``` has the complete MI-Net model class which imports submodules from both ```backbones.py``` and ```modules.py```. What I suggest you to do is to simply copy these architectures.
- Specifically in ```src/Learning/Models/MotionIMG/backbones.py``` the "BaselineCNN_backbone()" class and the "Motion_decoder()" class form the encoder-decoder structure of the MI-Net. If you are interested in the concept of the motion image and you wanted to start experimenting with it quickly these two classes are what you want to embed in your network.
- What the MI-Net returns is a tuple containing a vector (in my case actions but you can make it whatever you want) and the predicted motion image which can be trained with various losses, but I used pixelwise MSE.

I am truly sorry if I do not spend additional time formatting the code but I do not believe it would be worth it. What I really care to share is the concept of the motion image and its use as a model prediction through an image encoder-decoder structure. Whereas I believe the actual implementation of this idea is very project-specific and might be easier to simply implement from scratch.

**Comment by happyflying-web** [comment]
Thank you！
